### PR TITLE
Clarify that cool sites are unalphabetized.

### PR DESCRIPTION
**Pull request by rsmoz**
Reduces liability potential of website by backing off of promise that list of “Cool Sites” is alphabetized. At the moment, the ordering is arbitrary and (coincidentally and meaninglessly) happens to be identical to a true alphabetized list. However, the logistical burden of maintaining such a promise into the future, as sites are created and destroyed, as well as the potential for public humiliation at failing at what is widely (but incorrectly) perceived to be a profoundly simple task, greatly outweigh any clerical advantages of alphabetization to the common PeterHajas.com clientele.

### CODE REVIEW

**Comment by rsmoz** [comment]
Would appreciate input from @buzzert, @zanneth, and @vivekseth on whether this change would result in diminished prestige for their listed websites.

**Comment by buzzert** [comment]
I'm still on top, so LGTM.

**Comment by zanneth** [comment]
I’m still at the bottom, needs work.

**Comment by vivekseth** [comment]
Great 2 character change, but all I really want is an extra `s` in the `http://` 😉

**Pull request closed without merging**
